## Import des modules

In [1]:
import json
from pandas import json_normalize
import pandas as pd
from datetime import date

# 1ère source de données : Offres d'alternance en France selon Pôle Emploi API

## Ouverture & Lecture des données dans les fichiers par zone française

In [2]:
with open("Meuse-Rognon_Nord_Est.json", "r", encoding="utf-8") as read_file:
    data_nord_est = json.load(read_file)
with open("Rennes_Ouest.json", "r", encoding="utf-8") as read_file:
    data_nord_ouest = json.load(read_file)
with open("VESDUN.json", "r", encoding="utf-8") as read_file:
    data_centre = json.load(read_file)
with open("chamaloc_sud est.json", "r", encoding="utf-8") as read_file:
    data_sud_est = json.load(read_file)
with open("Clermont_Nord.json", "r", encoding="utf-8") as read_file:
    data_nord = json.load(read_file)
with open("cologne_sud ouest.json", "r", encoding="utf-8") as read_file:
    data_sud_ouest = json.load(read_file)

## Comprendre la composition des fichiers

In [3]:
data_centre.keys()

dict_keys(['peJobs', 'lbaCompanies', 'lbbCompanies'])

json_normalize(data_centre['lbaCompanies']['results'][0])

In [4]:
#data_centre['peJobs']['results']

In [5]:
data_centre['peJobs']['results'][0]   #1ère élément de peJob

{'ideaType': 'peJob',
 'ideaWeight': 1000,
 'title': 'coiffeur/coiffeuse en alternance (CAP) (H/F)',
 'longTitle': None,
 'id': None,
 'contact': {},
 'place': {'distance': 239.2,
  'insee': '91421',
  'zipCode': '91230',
  'city': '91 - MONTGERON',
  'latitude': 48.704816,
  'longitude': 2.455399,
  'fullAddress': '91 - MONTGERON 91230'},
 'company': {'name': 'FRANCK PROVOST'},
 'diplomaLevel': None,
 'diploma': None,
 'cfd': None,
 'rncpCode': None,
 'rncpLabel': None,
 'rncpEligibleApprentissage': None,
 'period': None,
 'capacity': None,
 'createdAt': None,
 'lastUpdateAt': None,
 'onisepUrl': None,
 'url': 'https://candidat.pole-emploi.fr/offres/recherche/detail/112LDGW',
 'job': {'id': '112LDGW',
  'creationDate': '2021-04-06T14:08:56.000Z',
  'description': "salon FRANCK PROVOSTsitué en plein centre ville de Montgeron, à 5 minutes a pieds de la gare, recherche dans  le cadre d'un  Contrat de Professionnalisation ou d'apprentissage pour l'obtention du CAP coiffure\nCentre de formation : Académie internationale Franck Provost ou le centre de votre choix.\n",
  'contractType': 'CDD',
  'contractDescription': 'Contrat à durée déterminée - 24 Mois',
  'duration': '35H Travail le samedi'},
 'romes': [{'code': 'D1202'}],
 'nafs': None}

## Création d'une liste pour concaténer toutes les données offres d'alternance des différentes zones françaises

In [6]:
df_list = []

df_list.append(json_normalize(data_centre['peJobs']['results']))

df_list.append(json_normalize(data_nord_est['peJobs']['results']))

df_list.append(json_normalize(data_nord_ouest['peJobs']['results']))

df_list.append(json_normalize(data_sud_est['peJobs']['results']))

df_list.append(json_normalize(data_nord['peJobs']['results']))

df_list.append(json_normalize(data_sud_ouest['peJobs']['results']))

jobs_df = pd.concat(df_list, axis=0)

jobs_df

,ideaType,ideaWeight,title,longTitle,id,diplomaLevel,diploma,cfd,rncpCode,rncpLabel,...,job.description,job.contractType,job.contractDescription,job.duration,contact.name,contact.info,contact,contact.email,company.description,company.logo
0,peJob,1000.0,coiffeur/coiffeuse en alternance (CAP) (H/F),None,None,None,None,None,None,None,...,salon FRANCK PROVOSTsitué en plein centre vill...,CDD,Contrat à durée déterminée - 24 Mois,35H Travail le samedi,NaN,NaN,NaN,NaN,NaN,NaN
1,peJob,1000.0,Coiffeur / Coiffeuse,None,None,None,None,None,None,None,...,Apprenti (e) coiffeur (se)\nSuivant modalités ...,CDD,Contrat à durée déterminée - 24 Mois,35H Horaires normaux,Pôle Emploi Arpajon,"2 ROUTE d'Egly\n91290 ARPAJON\nPour postuler, ...",NaN,NaN,NaN,NaN
2,peJob,1000.0,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,None,None,None,None,None,None,None,...,"Dans ce cadre, vous serez amené(e) à :\n\nPart...",CDD,Contrat à durée déterminée - 24 Mois,35H Horaires normaux,NaN,https://sanofi.wd3.myworkdayjobs.com/StudentPr...,NaN,NaN,NaN,NaN
3,peJob,1000.0,Préparateur / Préparatrice de commandes (H/F),None,None,None,None,None,None,None,...,Description du poste :\nSTEF recrute pour sa f...,CDD,Contrat à durée déterminée - 12 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,peJob,1000.0,Agent / Agente logistique en magasinage (H/F),None,None,None,None,None,None,None,...,Description du poste :\nSTEF recrute pour sa f...,CDD,Contrat à durée déterminée - 12 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,peJob,1000.0,Préparateur / Préparatrice de commandes (H/F),None,None,None,None,None,None,None,...,Une grande chaine de boulangerie recherche un(...,CDD,Contrat à durée déterminée - 12 Mois,35H Horaires normaux,CESAME SUP - Mme Junior Genevieve,"Pour postuler, utiliser le lien suivant : http...",NaN,"Pour postuler, utiliser le lien suivant : http...",Une grande chaine de boulangerie recherche un(...,https://entreprise.pole-emploi.fr/static/img/l...
32,peJob,1000.0,Préparateur / Préparatrice de commandes (H/F),None,None,None,None,None,None,None,...,Préparateur(trice) de commandes en apprentissa...,CDD,Contrat à durée déterminée - 24 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,peJob,1000.0,Préparateur / Préparatrice de commandes (H/F),None,None,None,None,None,None,None,...,Préparateur(trice) de commandes en apprentissa...,CDD,Contrat à durée déterminée - 24 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,peJob,1000.0,Préparateur / Préparatrice de commandes (H/F),None,None,None,None,None,None,None,...,Préparateur(trice) de commandes en apprentissa...,CDD,Contrat à durée déterminée - 24 Mois,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,peJob,1000.0,Magasinier vendeur / Magasinière vendeuse (H/F),None,None,None,None,None,None,None,...,Nous recherchons pour un de nos partenaires sp...,CDD,Contrat à durée déterminée - 24 Mois,35H Horaires normaux,Pôle Emploi LE PUY EN VELAY,5 RUE DES CHEVALIERS ST JEAN\nCS 70180\n43009 ...,NaN,NaN,NaN,NaN

In [7]:
#DataFrame, colonnes utiles :

jobs_df[['job.creationDate','title','place.city','place.zipCode','company.name','place.latitude', 'place.longitude']]

,job.creationDate,title,place.city,place.zipCode,company.name,place.latitude,place.longitude
0,2021-04-06T14:08:56.000Z,coiffeur/coiffeuse en alternance (CAP) (H/F),91 - MONTGERON,91230,FRANCK PROVOST,48.704816,2.455399
1,2021-02-04T17:25:49.000Z,Coiffeur / Coiffeuse,91 - OLLAINVILLE,91340,Salon des terrasses,48.599400,2.227350
2,2021-04-08T15:55:42.000Z,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,69 - NEUVILLE SUR SAONE,69250,SANOFI-AVENTIS GROUPE,45.878996,4.838026
3,2021-03-21T08:59:42.000Z,Préparateur / Préparatrice de commandes (H/F),91 - ATHIS MONS,91200,NaN,48.708960,2.384591
4,2021-03-22T17:45:11.000Z,Agent / Agente logistique en magasinage (H/F),91 - ATHIS MONS,91200,NaN,48.708960,2.384591
...,...,...,...,...,...,...,...
31,2021-03-05T14:59:14.000Z,Préparateur / Préparatrice de commandes (H/F),34 - LE CRES,34920,CESAME SUP,43.653024,3.937211
32,2021-04-09T19:15:45.000Z,Préparateur / Préparatrice de commandes (H/F),34 - PEROLS,34470,CFA TRANSPORT ET LOGISTIQUE AFTRAL,43.567338,3.952259
33,2021-03-23T20:04:01.000Z,Préparateur / Préparatrice de commandes (H/F),34 - ST AUNES,34130,CFA TRANSPORT ET LOGISTIQUE AFTRAL,43.636046,3.969501
34,2021-04-09T19:16:05.000Z,Préparateur / Préparatrice de commandes (H/F),34 - BOISSERON,34160,CFA TRANSPORT ET LOGISTIQUE AFTRAL,43.755872,4.076496
35,2021-02-05T11:16:16.000Z,Magasinier vendeur / Magasinière vendeuse (H/F),43 - PRADELLES,43420,DEA FORMATION,44.768012,3.883394

In [8]:
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518 entries, 0 to 35
Data columns (total 39 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ideaType                   518 non-null    object
 1   ideaWeight                 518 non-null    float64
 2   title                      518 non-null    object
 3   longTitle                  0 non-null      object
 4   id                         0 non-null      object
 5   diplomaLevel               0 non-null      object
 6   diploma                    0 non-null      object
 7   cfd                        0 non-null      object
 8   rncpCode                   0 non-null      object
 9   rncpLabel                  0 non-null      object
 10  rncpEligibleApprentissage  0 non-null      object
 11  period                     0 non-null      object
 12  capacity                   0 non-null      object
 13  createdAt                  0 non-null      object
 14  lastUpdateAt               0 non-null      object
 15  onisepUrl                  0 non-null      object
 16  url                        518 non-null    object
 17  romes                      518 non-null    object
 18  nafs                       0 non-null      object
 19  place.distance             512 non-null    float64
 20  place.insee                512 non-null    object
 21  place.zipCode              512 non-null    object
 22  place.city                 518 non-null    object
 23  place.latitude             512 non-null    float64
 24  place.longitude            512 non-null    float64
 25  place.fullAddress          518 non-null    object
 26  company.name               258 non-null    object
 27  job.id                     518 non-null    object
 28  job.creationDate           518 non-null    object
 29  job.description            518 non-null    object
 30  job.contractType           518 non-null    object
 31  job.contractDescription    518 non-null    object
 32  job.duration               323 non-null    object
 33  contact.name               178 non-null    object
 34  contact.info               216 non-null    object
 35  contact                    0 non-null      float64
 36  contact.email              74 non-null     object
 37  company.description        93 non-null     object
 38  company.logo               57 non-null     object
dtypes: float64(5), object(34)
memory usage: 161.9+ KB

## Création des fonctions pour obtenir les n° de départements + les mois concernés

In [9]:
#Ajout d'une colonne pour n'obtenir que le n° du département

def get_department(x):
    return((x[:2]))

jobs_df['Dpt'] = jobs_df['place.zipCode'].apply(str).apply(get_department)

In [10]:
def get_month(x):
    return(x[0:7])

jobs_df['month'] = jobs_df['job.creationDate'].apply(get_month)

filtered_jobs_df = jobs_df[['job.creationDate','month','title','place.city','place.zipCode','Dpt','company.name']]

filtered_jobs_df

,job.creationDate,month,title,place.city,place.zipCode,Dpt,company.name
0,2021-04-06T14:08:56.000Z,2021-04,coiffeur/coiffeuse en alternance (CAP) (H/F),91 - MONTGERON,91230,91,FRANCK PROVOST
1,2021-02-04T17:25:49.000Z,2021-02,Coiffeur / Coiffeuse,91 - OLLAINVILLE,91340,91,Salon des terrasses
2,2021-04-08T15:55:42.000Z,2021-04,UN ALTERNANT - CHARGE DE PROJET FORMATION DIGI...,69 - NEUVILLE SUR SAONE,69250,69,SANOFI-AVENTIS GROUPE
3,2021-03-21T08:59:42.000Z,2021-03,Préparateur / Préparatrice de commandes (H/F),91 - ATHIS MONS,91200,91,NaN
4,2021-03-22T17:45:11.000Z,2021-03,Agent / Agente logistique en magasinage (H/F),91 - ATHIS MONS,91200,91,NaN
...,...,...,...,...,...,...,...
31,2021-03-05T14:59:14.000Z,2021-03,Préparateur / Préparatrice de commandes (H/F),34 - LE CRES,34920,34,CESAME SUP
32,2021-04-09T19:15:45.000Z,2021-04,Préparateur / Préparatrice de commandes (H/F),34 - PEROLS,34470,34,CFA TRANSPORT ET LOGISTIQUE AFTRAL
33,2021-03-23T20:04:01.000Z,2021-03,Préparateur / Préparatrice de commandes (H/F),34 - ST AUNES,34130,34,CFA TRANSPORT ET LOGISTIQUE AFTRAL
34,2021-04-09T19:16:05.000Z,2021-04,Préparateur / Préparatrice de commandes (H/F),34 - BOISSERON,34160,34,CFA TRANSPORT ET LOGISTIQUE AFTRAL
35,2021-02-05T11:16:16.000Z,2021-02,Magasinier vendeur / Magasinière vendeuse (H/F),43 - PRADELLES,43420,43,DEA FORMATION

# 2ème source de données = synthèse situation COVID-19 en France

## Ouverture & Lecture des données

In [56]:
data_covid = pd.read_csv('table-indicateurs-open-data-dep-2021-04-09-20h00.csv')

covid_df = pd.DataFrame(data_covid)

#covid_df a initialement 39188 entrées

C:\Users\amandine.gauberville\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

## Obtenir les mois en fonction de la date d'analyse

In [57]:
covid_df['month'] = covid_df['date'].apply(get_month)

## Transformer les dates dans le bon format dans le but de pouvoir appliquer un filtre

In [67]:
covid_df['date'] = pd.to_datetime(covid_df['date'], format='%Y-%m-%d')

In [59]:
covid_df[['dep', 'date', 'month', 'tx_incid']]

       dep        date    month   tx_incid
0       01  2020-03-18  2020-03        NaN
1       01  2020-03-19  2020-03        NaN
2       01  2020-03-20  2020-03        NaN
3       01  2020-03-21  2020-03        NaN
4       01  2020-03-22  2020-03        NaN
...    ...         ...      ...        ...
39183  976  2021-04-05  2021-04  51.168100
39184  976  2021-04-06  2021-04  53.315013
39185  976  2021-04-07  2021-04        NaN
39186  976  2021-04-08  2021-04        NaN
39187  976  2021-04-09  2021-04        NaN

[39188 rows x 4 columns]

## Création d'un filtre pour n'obtenir les dates qu'à partir du 01-08-2021

In [72]:
mask = (covid_df['date'] > '2020-08-1') & (covid_df['date'] <= '2021-04-11')
filtered_covid_df=covid_df.loc[mask]
data_covid_df = filtered_covid_df[['dep', 'date', 'month', 'tx_incid']]
data_covid_df

#filtered_covid_df a désormais 25351 entrées

       dep       date    month   tx_incid
137     01 2020-08-02  2020-08  10.807437
138     01 2020-08-03  2020-08  10.198568
139     01 2020-08-04  2020-08  10.807437
140     01 2020-08-05  2020-08  11.264090
141     01 2020-08-06  2020-08  10.959655
...    ...        ...      ...        ...
39183  976 2021-04-05  2021-04  51.168100
39184  976 2021-04-06  2021-04  53.315013
39185  976 2021-04-07  2021-04        NaN
39186  976 2021-04-08  2021-04        NaN
39187  976 2021-04-09  2021-04        NaN

[25351 rows x 4 columns]

In [61]:
#mean_tx_incid_per_month = per_month.groupby('dep', as_index=False).agg({'tx_incid':'mean'}) erreur car ne tient pas compte des départements.

## Ne choisir que les jours 15 du mois

In [74]:
final_data_covid_df = data_covid_df[data_covid_df.date.dt.day == 15]

# Exportation des 2 fichiers en .csv pour enregistrement dans une base de données SQL

In [75]:
#Export 1ère source de données :

final_data_covid_df.to_csv('data-offres-alternance2.csv', index=False)

#Export 2ème source de données :

data_covid_def.to_csv('data-covid-incidence-dep.csv', index=False)

# Définition du taux d'incidence :

1. Activité épidémique (taux d'incidence)

Le taux d'incidence correspond au nombre de tests virologiques positifs pour 100.000 habitants sur une semaine. Il est calculé, à l'échelle départementale, de la manière suivante : (100000*nombre de cas positif)/population.

Trois niveaux ont été fixés pour cet indicateur :

vert : en dessous de 10 personnes testées positives sur 100.000 personnes testées, sur une semaine glissante ;
orange : au-delà de 10 personnes testées positives sur 100.000 personnes testées, sur une semaine glissante ;
rouge : au-delà de 50 personnes testées positives sur 100.000 personnes testées, sur une semaine glissante.